name: Build ILV-Linux ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: ${{ runner.os }}-pacman-${{ hashFiles('configs/releng/pacman.conf') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pacman-${{ hashFiles('configs/releng/pacman.conf') }}-

      - name: Install dependencies and init keyring
        run: |
          pacman -Syu --noconfirm archlinux-keyring aria2 archiso squashfs-tools dosfstools mtools base-devel reflector
          pacman-key --init || true
          pacman-key --populate archlinux || true
          reflector --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist

      - name: Setup Profile
        run: |
          cd configs/releng/
          find . -name "mkinitcpio.conf" -delete
          find . -name "mkinitcpio.d" -exec rm -rf {} +
      - name: Free Disk Space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /usr/local/lib/android
          rm -rf /opt/ghc
      - name: Build ISO
        run: |
          rm -rf /tmp/archiso-tmp ||true
          rm -rf out/ ||true
          mkdir -p out
          mkarchiso -v -w /tmp/archiso-tmp -o out/ configs/releng/
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ILV-Linux-ISO
          path: out/*.iso
          retention-days: 7
