name: Build ILV-Linux ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged --device=/dev/loop-control --device=/dev/loop0 --cap-add=SYS_ADMIN --cap-add=SYS_CHROOT
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: ${{ runner.os }}-pacman-${{ hashFiles('configs/releng/pacman.conf') }}-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-pacman-${{ hashFiles('configs/releng/pacman.conf') }}-

      - name: Install dependencies and init keyring
        run: |
          set -euo pipefail
          pacman -Sy --noconfirm archlinux-keyring aria2 archiso squashfs-tools dosfstools mtools base-devel reflector jq git github-cli curl bc wget unzip rsync
          pacman -S --noconfirm ncurses libelf perl texinfo
          pacman -Syu --noconfirm
          packages=(git bc bison bzip2 tar flex pahole elfutils openssl zstd kmod cpio gawk lld ccache patch pigz xz lz4 linux-headers glibc gcc-libs zlib perl python python-pip findutils grep sed coreutils util-linux linux-firmware procps-ng iproute2 dracut)
          for pkg in "${packages[@]}"; do pacman -S --noconfirm "$pkg"; done
          pacman-key --init || true
          pacman-key --populate archlinux || true
          reflector --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
          mkdir -p /opt/gcc-13
          curl -L https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64/tarballs/x86-64--glibc--bleeding-edge-2023.08-1.tar.bz2 | tar -xjC /opt/gcc-13 --strip-components=1
          echo "/opt/gcc-13/bin" >> $GITHUB_PATH
          export PATH="/opt/gcc-13/bin:$PATH"
          cd ..
          curl -O https://archive.archlinux.org/iso/2026.07.01/archlinux-bootstrap-2026.07.01-x86_64.tar.zst
          tar -I zstd -xvf archlinux-bootstrap-*.tar.zst
      - name: Build Rootfs
        run: |
          bash scripts/bootstrap.sh
          tar --numeric-owner --xattrs --acls -I 'zstd -19' -cf arch-hammer.tar.zst -C root.x86_64 .
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ILV-Linux-ISO
          path: /out/*.iso
